#!/bin/sh 

INTERACTIVE=1 
ALL=1 
INIT=1
PREPARE=1 
VIRTUAL=1 
DISPLAY=1 
PACKAGE=""
SALOME_VERSION=SALOME-9.16.0-macOS
INSTALLATION_FOLDER="$SALOME_VERSION"25.6.0 
SALOME_WORKSPACE=~/workspace/current

