#!/bin/sh 

INTERACTIVE=1 
ALL=1 
INIT=1
PREPARE=1 
VIRTUAL=1 
DISPLAY=1
PROGRESS_BAR=1
FRESH=1
UPDATE=1
PACKAGE=""
export SALOME_VERSION=SALOME-9.16.0-macOS
export INSTALLATION_FOLDER="$SALOME_VERSION"25
export SALOME_WORKSPACE=~/workspace/current
